version: "3"

services:
  cu_bot:
    image: dd/cu_bot:0.1.3-version
    container_name: cu_bot
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cu_db_postgres:5432/cu_db
      - SPRING_DATASOURCE_USERNAME=postgres_username
      - SPRING_DATASOURCE_PASSWORD=postgres_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - TZ=Europe/Moscow
    volumes:
      - ./config/:/config
    depends_on:
      - cu_db_postgres
      - flyway

  cu_db_postgres:
    container_name: cu_db
    image: postgres:15-alpine
    env_file:
      - dev.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres_db/data:/var/lib/postgresql/data
    restart: unless-stopped

  flyway:
    container_name: flyway
    image: flyway/flyway:10-alpine
    volumes:
        - ./flyway/db/migration:/flyway/sql
        - ./flyway/flyway.conf:/flyway/conf/flyway.config
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    depends_on:
        - cu_db_postgres
